### ISSUE TITLE
Text Alignment not working on non admin wagtail richtext editor

### ISSUE THREAD

**Issue by devlas-cl** [Nigel2392/globlocks#1]
Hello, I congratulate you on your work, it is the solution I was looking for.
**Describe the bug**
I have another plugin called 'wagtail-non-admin-draftail'
Everything works perfectly in the admin richtext editor, but when I try to view it in the non admin editor everything stops working, logically it should work since this plugin inherits all the functions of the normal draftail admin editor.

I only have the 'text-alignment' feature activated. When I remove it everything works correctly again.
**To Reproduce**
1. Go to a Page Editor and select a RichTextField to modify. All works OK
2. Go to wagtail-non-admin-draftail editor in my custom Pages

**Expected behavior**

**Screenshots**
https://imgur.com/a/YsVFGNL

**Additional context**
Wagtail 6.0.1

**Comment by Nigel2392** [comment]
Should be fixed in 1.2.0.
Are you including the hook output from `insert_global_admin_js` somewhere?
Translations were not available, these are included by the hook.
I'm falling back to hardcoded strings now.

Glad to know the text-alignment is useful. 😄 

*Edit*
1.2.3 also has support for lists in text-alignment.

**Comment by Nigel2392** [comment]
Refactored into separate package - I can imagine this is about the only feature you're using from this package as the other stuff isn't documented as of now.

https://github.com/Nigel2392/wagtail_text_alignment
